// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameAdministrator = "Administrators"

// Administrator mapped from table <Administrators>
type Administrator struct {
	FkUserid int32 `gorm:"column:fk_userid" json:"fk_userid"`
}

// TableName Administrator's table name
func (*Administrator) TableName() string {
	return TableNameAdministrator
}
