// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameCardsQueue = "CardsQueue"

// CardsQueue mapped from table <CardsQueue>
type CardsQueue struct {
	ID       int32 `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	FkCardid int32 `gorm:"column:fk_cardid;not null" json:"fk_cardid"`
	FkUserid int32 `gorm:"column:fk_userid;not null" json:"fk_userid"`
	Since    int32 `gorm:"column:since;not null" json:"since"`
	Until    int32 `gorm:"column:until" json:"until"`
	Returned bool  `gorm:"column:returned" json:"returned"`
	Reserved bool  `gorm:"column:reserved" json:"reserved"`
}

// TableName CardsQueue's table name
func (*CardsQueue) TableName() string {
	return TableNameCardsQueue
}
