// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameCard = "Cards"

// Card mapped from table <Cards>
type Card struct {
	ID              int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	FkStorageid     int32  `gorm:"column:fk_storageid;not null" json:"fk_storageid"`
	Position        int32  `gorm:"column:position;not null" json:"position"`
	Name            string `gorm:"column:name;not null" json:"name"`
	Readerdata      string `gorm:"column:readerdata" json:"readerdata"`
	Accesscount     int32  `gorm:"column:accesscount" json:"accesscount"`
	Iscardavailable bool   `gorm:"column:iscardavailable;not null;default:1" json:"iscardavailable"`
}

// TableName Card's table name
func (*Card) TableName() string {
	return TableNameCard
}
