// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameStorage = "Storages"

// Storage mapped from table <Storages>
type Storage struct {
	ID       int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Location string `gorm:"column:location;not null" json:"location"`
	Name     string `gorm:"column:name;not null" json:"name"`
	Ipaddr   string `gorm:"column:ipaddr;not null" json:"ipaddr"`
	Capacity int32  `gorm:"column:capacity;not null;default:10" json:"capacity"`
}

// TableName Storage's table name
func (*Storage) TableName() string {
	return TableNameStorage
}
