// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUser = "Users"

// User mapped from table <Users>
type User struct {
	ID         int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Email      string `gorm:"column:email;not null" json:"email"`
	Readerdata string `gorm:"column:readerdata" json:"readerdata"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
