// Code generated by go-enum DO NOT EDIT.
// Version: 0.5.3
// Revision: 8e2c93debfc66888870b2dfd86e70c79a70c920f
// Build Date: 2022-11-09T16:39:46Z
// Built By: goreleaser

package controller

import (
	"errors"
	"fmt"
)

const (
	// ActionStorageUnitPing is a Action of type storage-unit-ping.
	ActionStorageUnitPing Action = "storage-unit-ping"
	// ActionStorageUnitNewCard is a Action of type storage-unit-new-card.
	ActionStorageUnitNewCard Action = "storage-unit-new-card"
	// ActionStorageUnitDeleteCard is a Action of type storage-unit-delete-card.
	ActionStorageUnitDeleteCard Action = "storage-unit-delete-card"
	// ActionStorageUnitFetchCardSourceMobile is a Action of type storage-unit-fetch-card-source-mobile.
	ActionStorageUnitFetchCardSourceMobile Action = "storage-unit-fetch-card-source-mobile"
	// ActionStorageUnitFetchCardSourceTerminal is a Action of type storage-unit-fetch-card-source-terminal.
	ActionStorageUnitFetchCardSourceTerminal Action = "storage-unit-fetch-card-source-terminal"
	// ActionStorageUnitDepositCard is a Action of type storage-unit-deposit-card.
	ActionStorageUnitDepositCard Action = "storage-unit-deposit-card"
	// ActionUserSignup is a Action of type user-signup.
	ActionUserSignup Action = "user-signup"
)

var ErrInvalidAction = errors.New("not a valid Action")

// String implements the Stringer interface.
func (x Action) String() string {
	return string(x)
}

// String implements the Stringer interface.
func (x Action) IsValid() bool {
	_, err := ParseAction(string(x))
	return err == nil
}

var _ActionValue = map[string]Action{
	"storage-unit-ping":                       ActionStorageUnitPing,
	"storage-unit-new-card":                   ActionStorageUnitNewCard,
	"storage-unit-delete-card":                ActionStorageUnitDeleteCard,
	"storage-unit-fetch-card-source-mobile":   ActionStorageUnitFetchCardSourceMobile,
	"storage-unit-fetch-card-source-terminal": ActionStorageUnitFetchCardSourceTerminal,
	"storage-unit-deposit-card":               ActionStorageUnitDepositCard,
	"user-signup":                             ActionUserSignup,
}

// ParseAction attempts to convert a string to a Action.
func ParseAction(name string) (Action, error) {
	if x, ok := _ActionValue[name]; ok {
		return x, nil
	}
	return Action(""), fmt.Errorf("%s is %w", name, ErrInvalidAction)
}

// MarshalText implements the text marshaller method.
func (x Action) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *Action) UnmarshalText(text []byte) error {
	tmp, err := ParseAction(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}
