name: card_master
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1
environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies: 
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  web_socket_channel: ^2.3.0
  provider: ^6.0.5
  shared_preferences: ^2.0.17
  flutter_dotenv: ^5.0.2
  flutter_local_notifications: ^9.6.0
  rxdart: ^0.27.7
  app_settings: ^4.2.0
  open_mail_app: ^0.4.5
  intl: ^0.17.0
  awesome_snackbar_content: ^0.1.0
  flutter_datetime_picker: ^1.5.1
  tuple: ^2.0.1
  aad_oauth: ^0.4.0
  charts_flutter: ^0.12.0
  sizer: ^2.0.15
  http: any
  flutter_app_name: ^0.1.1
  flutter_launcher_icons: ^0.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_icons:
  image_path: "assets/icon.png"
  android: true
  ios: true
  min_sdk_android: 21

flutter_app_name:
  name: "Card Storage Management"

flutter:
  assets:
    - img/
    - assets/azure.env

  uses-material-design: true
  fonts:
    - family: Kanit
      fonts:
        - asset: fonts/Kanit/Kanit-Light.ttf
          weight: 300
        - asset: fonts/Kanit/Kanit-Thin.ttf
          weight: 400
        - asset: fonts/Kanit/Kanit-Medium.ttf
          weight: 500
        - asset: fonts/Kanit/Kanit-Bold.ttf
          weight: 600
        - asset: fonts/Kanit/Kanit-ExtraBold.ttf
          weight: 700
