name: card_master
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.

version: 1.0.0+1
environment:
  sdk: '>=2.18.5 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
dependencies: 
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  web_socket_channel: ^2.3.0
  provider: ^6.0.5
  shared_preferences: ^2.0.17
  flutter_dotenv: ^5.0.2
  flutter_secure_storage: ^5.0.2
  flutter_local_notifications: ^9.6.0
  rxdart: ^0.27.7
  app_settings: ^4.2.0
  open_mail_app: ^0.4.5
  intl: ^0.17.0
  awesome_snackbar_content: ^0.1.0
  flutter_datetime_picker: ^1.5.1
  tuple: ^2.0.1
  aad_oauth: ^0.4.0
  charts_flutter: ^0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
# The following section is specific to Flutter packages.
flutter:
  assets:
    - img/
    - azure.env
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  fonts:
    - family: Kanit
      fonts:
        - asset: fonts/Kanit/Kanit-Light.ttf
          weight: 300
        - asset: fonts/Kanit/Kanit-Thin.ttf
          weight: 400
        - asset: fonts/Kanit/Kanit-Medium.ttf
          weight: 500
        - asset: fonts/Kanit/Kanit-Bold.ttf
          weight: 600
        - asset: fonts/Kanit/Kanit-ExtraBold.ttf
          weight: 700
